### ISSUE TITLE
BlobCache & WP Rocket

### ISSUE THREAD

**Issue by EstebanChaves** [ProjectNami/ProjectNamiBlobCache#4]
Hi, Do you recommend to use BlobCache & Wp Rocket, working together?

**Comment by patrickebates** [comment]
Not familiar with WP Rocket, but looking over their feature list I do see the following areas of overlap.
- Page Caching
- Browser Caching (in our case, for the page data itself)
- Mobile Detection
- Multisite Compatibility (though at the moment you don't want to attempt Network Activation of the plugin)

Since you're running in IIS or Azure Web Apps, you also need to consider the following...
- GZIP Compression can be handled by settings in IIS or web.config, and on Azure Web Apps it should be enabled by default for many content types
- Some plugin features may require services which IIS cannot provide (such as Enhanced Disk Cache from W3TC requiring .htaccess files). This was a key reason behind our creation of Blob Cache as an IIS Module.

**Comment by EstebanChaves** [comment]
Thanks for your reply.
